/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_alejandroosorto;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ale
 */
public class PRINCIPAL extends javax.swing.JFrame
{

    /**
     * Creates new form PRINCIPAL
     */
    
    String nombreCliente = "";
    int IDCliente = 0;
    
    int Pollos;
    int Biscs;
    int Pur;
    int Papas;
    int fresc;
    int pies;
    
    public PRINCIPAL()
    {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        JD_CLIENTE = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CT_Nombre_CLIENTE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CT_ID_CLIENTE = new javax.swing.JTextField();
        BTN_INGRESAR_CLIENTE = new javax.swing.JButton();
        BTN_NUEVOCLIENTE_CLIENTE = new javax.swing.JButton();
        JD_NUEVOCLIENTE = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CT_Nombre_NUEVOCLIENTE = new javax.swing.JTextField();
        CT_Apellido_NUEVOCLIENTE = new javax.swing.JTextField();
        CT_ID_NUEVOCLIENTE = new javax.swing.JTextField();
        BTN_REGISTRACLIENTE_NUEVOCLIENTE = new javax.swing.JButton();
        JD_REGISTRO = new javax.swing.JDialog();
        JD_MENU = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JS_Pollo = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JS_Bisc = new javax.swing.JSpinner();
        JS_Pur = new javax.swing.JSpinner();
        JS_Papas = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        JS_fresco = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        JS_Pie = new javax.swing.JSpinner();
        BTN_SIMULAR_MENU = new javax.swing.JButton();
        BTN_CANCELAR_SIMULACION = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        JD_SIMULACION = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        BTN_INICORDEN_SIMULACION = new javax.swing.JButton();
        PB_BarraSimulacion = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_Elementos = new javax.swing.JTable();
        BTN_FINSIMULACION_SIMULACION = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        L_Elemento = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MI_CLIENTE = new javax.swing.JMenuItem();
        MI_NUEVOCLIENTE = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MI_REGISTRO = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MI_CerrSes = new javax.swing.JMenuItem();

        JD_CLIENTE.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_CLIENTE.setTitle("CLIENTE");

        jPanel2.setBackground(new java.awt.Color(127, 151, 168));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INGRESAR COMO CLIENTE");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID:");

        CT_ID_CLIENTE.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CT_ID_CLIENTEKeyTyped(evt);
            }
        });

        BTN_INGRESAR_CLIENTE.setText("Ingresar");
        BTN_INGRESAR_CLIENTE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BTN_INGRESAR_CLIENTEMouseClicked(evt);
            }
        });

        BTN_NUEVOCLIENTE_CLIENTE.setBackground(new java.awt.Color(127, 151, 168));
        BTN_NUEVOCLIENTE_CLIENTE.setForeground(new java.awt.Color(0, 0, 0));
        BTN_NUEVOCLIENTE_CLIENTE.setText("Nuevo Cliente");
        BTN_NUEVOCLIENTE_CLIENTE.setBorder(null);
        BTN_NUEVOCLIENTE_CLIENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_NUEVOCLIENTE_CLIENTE.setOpaque(true);
        BTN_NUEVOCLIENTE_CLIENTE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BTN_NUEVOCLIENTE_CLIENTEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(BTN_NUEVOCLIENTE_CLIENTE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_INGRESAR_CLIENTE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(49, 49, 49)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CT_Nombre_CLIENTE)
                                .addComponent(CT_ID_CLIENTE, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CT_Nombre_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CT_ID_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_INGRESAR_CLIENTE)
                    .addComponent(BTN_NUEVOCLIENTE_CLIENTE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_CLIENTELayout = new javax.swing.GroupLayout(JD_CLIENTE.getContentPane());
        JD_CLIENTE.getContentPane().setLayout(JD_CLIENTELayout);
        JD_CLIENTELayout.setHorizontalGroup(
            JD_CLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_CLIENTELayout.setVerticalGroup(
            JD_CLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JD_NUEVOCLIENTE.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_NUEVOCLIENTE.setTitle("NUEVO CLIENTE");

        jPanel3.setBackground(new java.awt.Color(111, 148, 172));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NUEVO CLIENTE");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ingrese Nombre:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ingrese Apellido:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ingrese su ID:");

        CT_ID_NUEVOCLIENTE.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CT_ID_NUEVOCLIENTEKeyTyped(evt);
            }
        });

        BTN_REGISTRACLIENTE_NUEVOCLIENTE.setText("Registrar Nuevo Cliente");
        BTN_REGISTRACLIENTE_NUEVOCLIENTE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_REGISTRACLIENTE_NUEVOCLIENTE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CT_ID_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CT_Apellido_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CT_Nombre_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CT_Nombre_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CT_Apellido_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CT_ID_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(BTN_REGISTRACLIENTE_NUEVOCLIENTE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_NUEVOCLIENTELayout = new javax.swing.GroupLayout(JD_NUEVOCLIENTE.getContentPane());
        JD_NUEVOCLIENTE.getContentPane().setLayout(JD_NUEVOCLIENTELayout);
        JD_NUEVOCLIENTELayout.setHorizontalGroup(
            JD_NUEVOCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_NUEVOCLIENTELayout.setVerticalGroup(
            JD_NUEVOCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JD_REGISTRO.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_REGISTRO.setTitle("REGISTRO");

        javax.swing.GroupLayout JD_REGISTROLayout = new javax.swing.GroupLayout(JD_REGISTRO.getContentPane());
        JD_REGISTRO.getContentPane().setLayout(JD_REGISTROLayout);
        JD_REGISTROLayout.setHorizontalGroup(
            JD_REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_REGISTROLayout.setVerticalGroup(
            JD_REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(148, 181, 203));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("MENÚ");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Piezas de Pollo:");

        JS_Pollo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Biscuits:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Puré:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Papas:");

        JS_Bisc.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        JS_Pur.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        JS_Papas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Refrescos:");

        JS_fresco.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Pie:");

        JS_Pie.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        BTN_SIMULAR_MENU.setText("Confirmar orden(Simulación)");
        BTN_SIMULAR_MENU.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BTN_SIMULAR_MENUMouseClicked(evt);
            }
        });

        BTN_CANCELAR_SIMULACION.setText("Cancelar");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nota: Cada elemento tarda cierto tiempo en prepararse.");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Pollo: 4 Minutos c/u.");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Biscuits: 1 minuto c/u.");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Puré: 2 minutos c/u.");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Papas: 3 minutos c/u.");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Refrescos: 1 minuto c/u.");

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Pie: 5 minutos.");

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Nota extra: En este mundo el tiempo va más rápido,");
        jLabel22.setToolTipText("");

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("cada minuto aquí es un segundo en el mundo real.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_CANCELAR_SIMULACION)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_SIMULAR_MENU)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JS_Pie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JS_Papas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JS_Bisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(JS_Pollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JS_Pur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                        .addComponent(JS_fresco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel19))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel20))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(168, 168, 168))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JS_Pollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JS_Bisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(JS_Pur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JS_Papas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(JS_fresco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(JS_Pie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_CANCELAR_SIMULACION)
                    .addComponent(BTN_SIMULAR_MENU))
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_MENULayout = new javax.swing.GroupLayout(JD_MENU.getContentPane());
        JD_MENU.getContentPane().setLayout(JD_MENULayout);
        JD_MENULayout.setHorizontalGroup(
            JD_MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JD_MENULayout.setVerticalGroup(
            JD_MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(115, 159, 189));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("SIMULACION");

        BTN_INICORDEN_SIMULACION.setText("Iniciar Orden");
        BTN_INICORDEN_SIMULACION.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BTN_INICORDEN_SIMULACIONMouseClicked(evt);
            }
        });
        BTN_INICORDEN_SIMULACION.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BTN_INICORDEN_SIMULACIONActionPerformed(evt);
            }
        });

        T_Elementos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Número Orden", "Elemento", "Tiempo"
            }
        ));
        jScrollPane1.setViewportView(T_Elementos);

        BTN_FINSIMULACION_SIMULACION.setText("Finalizar Simulación");
        BTN_FINSIMULACION_SIMULACION.setEnabled(false);

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Preparando:");

        L_Elemento.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(jLabel24))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTN_INICORDEN_SIMULACION)
                                    .addComponent(PB_BarraSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(L_Elemento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTN_FINSIMULACION_SIMULACION)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(BTN_INICORDEN_SIMULACION)
                        .addGap(28, 28, 28)
                        .addComponent(PB_BarraSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(L_Elemento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(BTN_FINSIMULACION_SIMULACION)
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_SIMULACIONLayout = new javax.swing.GroupLayout(JD_SIMULACION.getContentPane());
        JD_SIMULACION.getContentPane().setLayout(JD_SIMULACIONLayout);
        JD_SIMULACIONLayout.setHorizontalGroup(
            JD_SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_SIMULACIONLayout.setVerticalGroup(
            JD_SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        MI_CLIENTE.setText("Ingresar Cliente Existente");
        MI_CLIENTE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MI_CLIENTEActionPerformed(evt);
            }
        });
        jMenu1.add(MI_CLIENTE);

        MI_NUEVOCLIENTE.setText("Nuevo Cliente");
        MI_NUEVOCLIENTE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MI_NUEVOCLIENTEActionPerformed(evt);
            }
        });
        jMenu1.add(MI_NUEVOCLIENTE);
        jMenu1.add(jSeparator1);

        MI_REGISTRO.setText("Registro de Órdenes");
        MI_REGISTRO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MI_REGISTROActionPerformed(evt);
            }
        });
        jMenu1.add(MI_REGISTRO);
        jMenu1.add(jSeparator2);

        MI_CerrSes.setText("Cerrar Sesión");
        MI_CerrSes.setEnabled(false);
        MI_CerrSes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MI_CerrSesActionPerformed(evt);
            }
        });
        jMenu1.add(MI_CerrSes);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MI_CLIENTEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MI_CLIENTEActionPerformed
    {//GEN-HEADEREND:event_MI_CLIENTEActionPerformed
        // TODO add your handling code here:
        Abrir_CLIENTE();
    }//GEN-LAST:event_MI_CLIENTEActionPerformed

    private void BTN_INGRESAR_CLIENTEMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BTN_INGRESAR_CLIENTEMouseClicked
    {//GEN-HEADEREND:event_BTN_INGRESAR_CLIENTEMouseClicked
        // TODO add your handling code here:
        if (CT_Nombre_CLIENTE.getText().isEmpty() || CT_ID_CLIENTE.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Uno o más campos están vacíos.");
        }
        else
        {
            String nombre = CT_Nombre_CLIENTE.getText();
            int ID = Integer.parseInt(CT_ID_CLIENTE.getText());
            
            AdminCliente AC = new AdminCliente("./Clientes.aos");
            AC.CargarArchivo();
            ArrayList listaClientes = AC.getListaClientes();
            
            boolean nCheck = false;
            boolean ICheck = false;
            
            for (int i = 0; i < listaClientes.size(); i++)
            {
                if (((Cliente)listaClientes.get(i)).getNombre().equals(nombre))
                {
                    nCheck = true;
                    if (((Cliente)listaClientes.get(i)).getID() == ID)
                    {
                        ICheck = true;
                        break;
                    }
                    else
                    {
                        nCheck = false;
                        ICheck = false;
                    }
                }
            }
            
            if (nCheck == true && ICheck == true)
            {
                JOptionPane.showMessageDialog(this, "Bienvenido Cliente.");
                nombreCliente = nombre;
                IDCliente = ID;
                CT_Nombre_CLIENTE.setText("");
                CT_ID_CLIENTE.setText("");
                JD_CLIENTE.dispose();
                
                MI_CLIENTE.setEnabled(false);
                MI_NUEVOCLIENTE.setEnabled(false);
                MI_CerrSes.setEnabled(true);
                
                Abrir_MENU();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Datos ingresados incorrectos.");
            }
        }
    }//GEN-LAST:event_BTN_INGRESAR_CLIENTEMouseClicked

    private void BTN_NUEVOCLIENTE_CLIENTEMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BTN_NUEVOCLIENTE_CLIENTEMouseClicked
    {//GEN-HEADEREND:event_BTN_NUEVOCLIENTE_CLIENTEMouseClicked
        // TODO add your handling code here:
        Abrir_NUEVOCLIENTE();
    }//GEN-LAST:event_BTN_NUEVOCLIENTE_CLIENTEMouseClicked

    private void MI_NUEVOCLIENTEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MI_NUEVOCLIENTEActionPerformed
    {//GEN-HEADEREND:event_MI_NUEVOCLIENTEActionPerformed
        // TODO add your handling code here:
        Abrir_NUEVOCLIENTE();
    }//GEN-LAST:event_MI_NUEVOCLIENTEActionPerformed

    private void MI_REGISTROActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MI_REGISTROActionPerformed
    {//GEN-HEADEREND:event_MI_REGISTROActionPerformed
        // TODO add your handling code here:
        Abrir_REGISTRO();
    }//GEN-LAST:event_MI_REGISTROActionPerformed

    private void BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked
    {//GEN-HEADEREND:event_BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked
        // TODO add your handling code here:
        if (CT_Nombre_NUEVOCLIENTE.getText().isEmpty() || CT_Apellido_NUEVOCLIENTE.getText().isEmpty() || CT_ID_NUEVOCLIENTE.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Uno o más campos están vacíos.");
        }
        else
        {
            String nombre = CT_Nombre_NUEVOCLIENTE.getText();
            String apellido = CT_Apellido_NUEVOCLIENTE.getText();
            int ID = Integer.parseInt(CT_ID_NUEVOCLIENTE.getText());
            Cliente c = new Cliente(nombre, apellido, ID);
            
            AdminCliente AC = new AdminCliente("./Clientes.aos");
            AC.CargarArchivo();
            AC.setClente(c);
            AC.ModificarArchivo();
            
            JOptionPane.showMessageDialog(this, "Nuevo Cliente agregado.");
        }
    }//GEN-LAST:event_BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked

    private void CT_ID_CLIENTEKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CT_ID_CLIENTEKeyTyped
    {//GEN-HEADEREND:event_CT_ID_CLIENTEKeyTyped
        // TODO add your handling code here:
        char check = evt.getKeyChar();
        
        if (Character.isLetter(check)) 
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(JD_CLIENTE, "Ingrese numeros solamente");
        }
    }//GEN-LAST:event_CT_ID_CLIENTEKeyTyped

    private void CT_ID_NUEVOCLIENTEKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CT_ID_NUEVOCLIENTEKeyTyped
    {//GEN-HEADEREND:event_CT_ID_NUEVOCLIENTEKeyTyped
        // TODO add your handling code here:
        char check = evt.getKeyChar();
        
        if (Character.isLetter(check)) 
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(JD_NUEVOCLIENTE, "Ingrese numeros solamente");
        }
    }//GEN-LAST:event_CT_ID_NUEVOCLIENTEKeyTyped

    private void BTN_SIMULAR_MENUMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BTN_SIMULAR_MENUMouseClicked
    {//GEN-HEADEREND:event_BTN_SIMULAR_MENUMouseClicked
        // TODO add your handling code here:
        if ((int)JS_Bisc.getValue() == 0 && (int)JS_Papas.getValue() == 0 && (int)JS_Pie.getValue() == 0 && (int)JS_Pollo.getValue() == 0 && (int)JS_Pur.getValue() == 0 && (int)JS_fresco.getValue() == 0)
        {
            JOptionPane.showMessageDialog(JD_MENU, "No se puede iniciar la simulacion si no se ha pedido nada.");
        }
        else
        {           
            Pollos = (int)JS_Pollo.getValue();
            Biscs = (int)JS_Bisc.getValue();
            Pur = (int)JS_Pur.getValue();
            Papas = (int)JS_Papas.getValue();
            fresc = (int)JS_fresco.getValue();
            pies = (int)JS_Pie.getValue();
            
            Orden o = new Orden(IDCliente, nombreCliente, Pollos, Biscs, Pur, Papas, fresc, pies);
            
            AdminOrden AO = new AdminOrden("./Ordenes.aos");
            AO.CargarArchivo();
            AO.setClente(o);
            AO.ModificarArchivo();
            
            JS_Bisc.setValue(0);
            JS_Papas.setValue(0);
            JS_Pie.setValue(0);
            JS_Pollo.setValue(0);
            JS_Pur.setValue(0);
            JS_fresco.setValue(0);
            JD_MENU.dispose();
            
            Abrir_SIMULACION();
        }
    }//GEN-LAST:event_BTN_SIMULAR_MENUMouseClicked

    private void BTN_INICORDEN_SIMULACIONMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BTN_INICORDEN_SIMULACIONMouseClicked
    {//GEN-HEADEREND:event_BTN_INICORDEN_SIMULACIONMouseClicked
        // TODO add your handling code here:
        //HP.start();
        //HB.start();
        //HPU.start();
        //HPA.start();
        //HF.start();
        //HPI.start();
        
        
        AdminBarra AB = new AdminBarra(PB_BarraSimulacion, T_Elementos, new Elementos(Pollos, Biscs, Pur, Papas, fresc, pies), L_Elemento);
        AB.start();
        
    }//GEN-LAST:event_BTN_INICORDEN_SIMULACIONMouseClicked

    private void MI_CerrSesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MI_CerrSesActionPerformed
    {//GEN-HEADEREND:event_MI_CerrSesActionPerformed
        // TODO add your handling code here:
        nombreCliente = "";
        IDCliente = 0;
        
        MI_CLIENTE.setEnabled(true);
        MI_NUEVOCLIENTE.setEnabled(true);
        MI_CerrSes.setEnabled(false);
    }//GEN-LAST:event_MI_CerrSesActionPerformed

    private void BTN_INICORDEN_SIMULACIONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BTN_INICORDEN_SIMULACIONActionPerformed
    {//GEN-HEADEREND:event_BTN_INICORDEN_SIMULACIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_INICORDEN_SIMULACIONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PRINCIPAL().setVisible(true);
            }
        });
    }
    
    public void Abrir_CLIENTE()
    {
        JD_CLIENTE.setModal(true);
        JD_CLIENTE.pack();
        JD_CLIENTE.setLocationRelativeTo(this);
        JD_CLIENTE.setVisible(true);
    }
    
    public void Abrir_NUEVOCLIENTE()
    {
        JD_NUEVOCLIENTE.setModal(true);
        JD_NUEVOCLIENTE.pack();
        JD_NUEVOCLIENTE.setLocationRelativeTo(this);
        JD_NUEVOCLIENTE.setVisible(true);
    }
    
    public void Abrir_REGISTRO()
    {
        JD_REGISTRO.setModal(true);
        JD_REGISTRO.pack();
        JD_REGISTRO.setLocationRelativeTo(this);
        JD_REGISTRO.setVisible(true);
    }
    
    public void Abrir_MENU()
    {
        JD_MENU.setModal(true);
        JD_MENU.pack();
        JD_MENU.setLocationRelativeTo(this);
        JD_MENU.setVisible(true);
    }
    
    public void Abrir_SIMULACION()
    {
        JD_SIMULACION.setModal(true);
        JD_SIMULACION.pack();
        JD_SIMULACION.setLocationRelativeTo(this);
        JD_SIMULACION.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CANCELAR_SIMULACION;
    private javax.swing.JButton BTN_FINSIMULACION_SIMULACION;
    private javax.swing.JButton BTN_INGRESAR_CLIENTE;
    private javax.swing.JButton BTN_INICORDEN_SIMULACION;
    private javax.swing.JButton BTN_NUEVOCLIENTE_CLIENTE;
    private javax.swing.JButton BTN_REGISTRACLIENTE_NUEVOCLIENTE;
    private javax.swing.JButton BTN_SIMULAR_MENU;
    private javax.swing.JTextField CT_Apellido_NUEVOCLIENTE;
    private javax.swing.JTextField CT_ID_CLIENTE;
    private javax.swing.JTextField CT_ID_NUEVOCLIENTE;
    private javax.swing.JTextField CT_Nombre_CLIENTE;
    private javax.swing.JTextField CT_Nombre_NUEVOCLIENTE;
    private javax.swing.JDialog JD_CLIENTE;
    private javax.swing.JDialog JD_MENU;
    private javax.swing.JDialog JD_NUEVOCLIENTE;
    private javax.swing.JDialog JD_REGISTRO;
    private javax.swing.JDialog JD_SIMULACION;
    private javax.swing.JSpinner JS_Bisc;
    private javax.swing.JSpinner JS_Papas;
    private javax.swing.JSpinner JS_Pie;
    private javax.swing.JSpinner JS_Pollo;
    private javax.swing.JSpinner JS_Pur;
    private javax.swing.JSpinner JS_fresco;
    private javax.swing.JLabel L_Elemento;
    private javax.swing.JMenuItem MI_CLIENTE;
    private javax.swing.JMenuItem MI_CerrSes;
    private javax.swing.JMenuItem MI_NUEVOCLIENTE;
    private javax.swing.JMenuItem MI_REGISTRO;
    private javax.swing.JProgressBar PB_BarraSimulacion;
    private javax.swing.JTable T_Elementos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
