/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_alejandroosorto;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ale
 */
public class PRINCIPAL extends javax.swing.JFrame
{

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL()
    {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        JD_CLIENTE = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CT_Nombre_CLIENTE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CT_ID_CLIENTE = new javax.swing.JTextField();
        BTN_INGRESAR_CLIENTE = new javax.swing.JButton();
        BTN_NUEVOCLIENTE_CLIENTE = new javax.swing.JButton();
        JD_NUEVOCLIENTE = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CT_Nombre_NUEVOCLIENTE = new javax.swing.JTextField();
        CT_Apellido_NUEVOCLIENTE = new javax.swing.JTextField();
        CT_ID_NUEVOCLIENTE = new javax.swing.JTextField();
        BTN_REGISTRACLIENTE_NUEVOCLIENTE = new javax.swing.JButton();
        JD_REGISTRO = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MI_CLIENTE = new javax.swing.JMenuItem();
        MI_NUEVOCLIENTE = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MI_REGISTRO = new javax.swing.JMenuItem();

        JD_CLIENTE.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_CLIENTE.setTitle("CLIENTE");

        jPanel2.setBackground(new java.awt.Color(127, 151, 168));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INGRESAR COMO CLIENTE");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID:");

        CT_ID_CLIENTE.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CT_ID_CLIENTEKeyTyped(evt);
            }
        });

        BTN_INGRESAR_CLIENTE.setText("Ingresar");
        BTN_INGRESAR_CLIENTE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BTN_INGRESAR_CLIENTEMouseClicked(evt);
            }
        });

        BTN_NUEVOCLIENTE_CLIENTE.setBackground(new java.awt.Color(127, 151, 168));
        BTN_NUEVOCLIENTE_CLIENTE.setForeground(new java.awt.Color(0, 0, 0));
        BTN_NUEVOCLIENTE_CLIENTE.setText("Nuevo Cliente");
        BTN_NUEVOCLIENTE_CLIENTE.setBorder(null);
        BTN_NUEVOCLIENTE_CLIENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_NUEVOCLIENTE_CLIENTE.setOpaque(true);
        BTN_NUEVOCLIENTE_CLIENTE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BTN_NUEVOCLIENTE_CLIENTEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(BTN_NUEVOCLIENTE_CLIENTE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_INGRESAR_CLIENTE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(49, 49, 49))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(82, 82, 82)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CT_Nombre_CLIENTE)
                                .addComponent(CT_ID_CLIENTE, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CT_Nombre_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CT_ID_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_INGRESAR_CLIENTE)
                    .addComponent(BTN_NUEVOCLIENTE_CLIENTE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_CLIENTELayout = new javax.swing.GroupLayout(JD_CLIENTE.getContentPane());
        JD_CLIENTE.getContentPane().setLayout(JD_CLIENTELayout);
        JD_CLIENTELayout.setHorizontalGroup(
            JD_CLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_CLIENTELayout.setVerticalGroup(
            JD_CLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JD_NUEVOCLIENTE.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_NUEVOCLIENTE.setTitle("NUEVO CLIENTE");

        jPanel3.setBackground(new java.awt.Color(111, 148, 172));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NUEVO CLIENTE");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ingrese Nombre:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ingrese Apellido:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ingrese su ID:");

        CT_ID_NUEVOCLIENTE.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CT_ID_NUEVOCLIENTEKeyTyped(evt);
            }
        });

        BTN_REGISTRACLIENTE_NUEVOCLIENTE.setText("Registrar Nuevo Cliente");
        BTN_REGISTRACLIENTE_NUEVOCLIENTE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_REGISTRACLIENTE_NUEVOCLIENTE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CT_ID_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CT_Apellido_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CT_Nombre_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CT_Nombre_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CT_Apellido_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CT_ID_NUEVOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(BTN_REGISTRACLIENTE_NUEVOCLIENTE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_NUEVOCLIENTELayout = new javax.swing.GroupLayout(JD_NUEVOCLIENTE.getContentPane());
        JD_NUEVOCLIENTE.getContentPane().setLayout(JD_NUEVOCLIENTELayout);
        JD_NUEVOCLIENTELayout.setHorizontalGroup(
            JD_NUEVOCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_NUEVOCLIENTELayout.setVerticalGroup(
            JD_NUEVOCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JD_REGISTRO.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_REGISTRO.setTitle("REGISTRO");

        javax.swing.GroupLayout JD_REGISTROLayout = new javax.swing.GroupLayout(JD_REGISTRO.getContentPane());
        JD_REGISTRO.getContentPane().setLayout(JD_REGISTROLayout);
        JD_REGISTROLayout.setHorizontalGroup(
            JD_REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_REGISTROLayout.setVerticalGroup(
            JD_REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        MI_CLIENTE.setText("Ingresar Cliente Existente");
        MI_CLIENTE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MI_CLIENTEActionPerformed(evt);
            }
        });
        jMenu1.add(MI_CLIENTE);

        MI_NUEVOCLIENTE.setText("Nuevo Cliente");
        MI_NUEVOCLIENTE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MI_NUEVOCLIENTEActionPerformed(evt);
            }
        });
        jMenu1.add(MI_NUEVOCLIENTE);
        jMenu1.add(jSeparator1);

        MI_REGISTRO.setText("Registro de Órdenes");
        MI_REGISTRO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MI_REGISTROActionPerformed(evt);
            }
        });
        jMenu1.add(MI_REGISTRO);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MI_CLIENTEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MI_CLIENTEActionPerformed
    {//GEN-HEADEREND:event_MI_CLIENTEActionPerformed
        // TODO add your handling code here:
        Abrir_CLIENTE();
    }//GEN-LAST:event_MI_CLIENTEActionPerformed

    private void BTN_INGRESAR_CLIENTEMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BTN_INGRESAR_CLIENTEMouseClicked
    {//GEN-HEADEREND:event_BTN_INGRESAR_CLIENTEMouseClicked
        // TODO add your handling code here:
        if (CT_Nombre_CLIENTE.getText().isEmpty() || CT_ID_CLIENTE.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Uno o más campos están vacíos.");
        }
        else
        {
            String nombre = CT_Nombre_CLIENTE.getText();
            int ID = Integer.parseInt(CT_ID_CLIENTE.getText());
            
            AdminCliente AC = new AdminCliente("./Clientes.aos");
            AC.CargarArchivo();
            ArrayList listaClientes = AC.getListaClientes();
            
            boolean nCheck = false;
            boolean ICheck = false;
            
            for (int i = 0; i < listaClientes.size(); i++)
            {
                if (((Cliente)listaClientes.get(i)).getNombre().equals(nombre))
                {
                    nCheck = true;
                    if (((Cliente)listaClientes.get(i)).getID() == ID)
                    {
                        ICheck = true;
                        break;
                    }
                    else
                    {
                        nCheck = false;
                        ICheck = false;
                    }
                }
            }
            
            if (nCheck == true && ICheck == true)
            {
                JOptionPane.showMessageDialog(this, "Bienvenido Cliente.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Datos ingresados incorrectos.");
            }
        }
    }//GEN-LAST:event_BTN_INGRESAR_CLIENTEMouseClicked

    private void BTN_NUEVOCLIENTE_CLIENTEMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BTN_NUEVOCLIENTE_CLIENTEMouseClicked
    {//GEN-HEADEREND:event_BTN_NUEVOCLIENTE_CLIENTEMouseClicked
        // TODO add your handling code here:
        Abrir_NUEVOCLIENTE();
    }//GEN-LAST:event_BTN_NUEVOCLIENTE_CLIENTEMouseClicked

    private void MI_NUEVOCLIENTEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MI_NUEVOCLIENTEActionPerformed
    {//GEN-HEADEREND:event_MI_NUEVOCLIENTEActionPerformed
        // TODO add your handling code here:
        Abrir_NUEVOCLIENTE();
    }//GEN-LAST:event_MI_NUEVOCLIENTEActionPerformed

    private void MI_REGISTROActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MI_REGISTROActionPerformed
    {//GEN-HEADEREND:event_MI_REGISTROActionPerformed
        // TODO add your handling code here:
        Abrir_REGISTRO();
    }//GEN-LAST:event_MI_REGISTROActionPerformed

    private void BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked
    {//GEN-HEADEREND:event_BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked
        // TODO add your handling code here:
        if (CT_Nombre_NUEVOCLIENTE.getText().isEmpty() || CT_Apellido_NUEVOCLIENTE.getText().isEmpty() || CT_ID_NUEVOCLIENTE.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Uno o más campos están vacíos.");
        }
        else
        {
            String nombre = CT_Nombre_NUEVOCLIENTE.getText();
            String apellido = CT_Apellido_NUEVOCLIENTE.getText();
            int ID = Integer.parseInt(CT_ID_NUEVOCLIENTE.getText());
            Cliente c = new Cliente(nombre, apellido, ID);
            
            AdminCliente AC = new AdminCliente("./Clientes.aos");
            AC.CargarArchivo();
            AC.setClente(c);
            AC.ModificarArchivo();
            
            JOptionPane.showMessageDialog(this, "Nuevo Cliente agregado.");
        }
    }//GEN-LAST:event_BTN_REGISTRACLIENTE_NUEVOCLIENTEMouseClicked

    private void CT_ID_CLIENTEKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CT_ID_CLIENTEKeyTyped
    {//GEN-HEADEREND:event_CT_ID_CLIENTEKeyTyped
        // TODO add your handling code here:
        char check = evt.getKeyChar();
        
        if (Character.isLetter(check)) 
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(JD_CLIENTE, "Ingrese numeros solamente");
        }
    }//GEN-LAST:event_CT_ID_CLIENTEKeyTyped

    private void CT_ID_NUEVOCLIENTEKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CT_ID_NUEVOCLIENTEKeyTyped
    {//GEN-HEADEREND:event_CT_ID_NUEVOCLIENTEKeyTyped
        // TODO add your handling code here:
        char check = evt.getKeyChar();
        
        if (Character.isLetter(check)) 
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(JD_NUEVOCLIENTE, "Ingrese numeros solamente");
        }
    }//GEN-LAST:event_CT_ID_NUEVOCLIENTEKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PRINCIPAL().setVisible(true);
            }
        });
    }
    
    public void Abrir_CLIENTE()
    {
        JD_CLIENTE.setModal(true);
        JD_CLIENTE.pack();
        JD_CLIENTE.setLocationRelativeTo(this);
        JD_CLIENTE.setVisible(true);
    }
    
    public void Abrir_NUEVOCLIENTE()
    {
        JD_NUEVOCLIENTE.setModal(true);
        JD_NUEVOCLIENTE.pack();
        JD_NUEVOCLIENTE.setLocationRelativeTo(this);
        JD_NUEVOCLIENTE.setVisible(true);
    }
    
    public void Abrir_REGISTRO()
    {
        JD_REGISTRO.setModal(true);
        JD_REGISTRO.pack();
        JD_REGISTRO.setLocationRelativeTo(this);
        JD_REGISTRO.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_INGRESAR_CLIENTE;
    private javax.swing.JButton BTN_NUEVOCLIENTE_CLIENTE;
    private javax.swing.JButton BTN_REGISTRACLIENTE_NUEVOCLIENTE;
    private javax.swing.JTextField CT_Apellido_NUEVOCLIENTE;
    private javax.swing.JTextField CT_ID_CLIENTE;
    private javax.swing.JTextField CT_ID_NUEVOCLIENTE;
    private javax.swing.JTextField CT_Nombre_CLIENTE;
    private javax.swing.JTextField CT_Nombre_NUEVOCLIENTE;
    private javax.swing.JDialog JD_CLIENTE;
    private javax.swing.JDialog JD_NUEVOCLIENTE;
    private javax.swing.JDialog JD_REGISTRO;
    private javax.swing.JMenuItem MI_CLIENTE;
    private javax.swing.JMenuItem MI_NUEVOCLIENTE;
    private javax.swing.JMenuItem MI_REGISTRO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
